### ISSUE TITLE
Make location map series for coastal team report

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#101]

**Comment by connorshank** [comment]
From Jenna's email:

Thanks for the additional guidance. I will see if I can get some shapefiles, I assume they exist for most if not all of these projects. 

These will be in a document (here is latest version https://app.box.com/s/sqx8xeaghwuu5w3as0cc069m051eet1r) as a report and also online at coastalresilience.org. I don't know whether it will actually be printed (Sarah, do you know?).

For sizing, I think quarter page for each case study and maybe half page for the one showing where all 5 are? If you think a quarter page map would show their relative location clearly then I think smaller is better, but I'll defer to your experience on what size is best for communication. 

Titles: I'm sure I'll modify these, but generally:
1.) A map showing the locations for the five case studies highlighted in this report: Seal Beach, Surfers' Point, San Francisco Bay Living Shorelines, Hamilton Wetland Restoration, and Humboldt Dunes.

2.) Seal Beach National Wildlife Refuge, location of thin layer sediment augmentation project.

3.) Surfers' Point, Ventura, CA.

4.) San Francisco Bay Living Shorelines Project location offshore from San Rafael (I'd like this map to show where in the bay this is, so not as zoomed in as their project map)

5.) Map highlighting the location of the Hamilton Wetland Restoration Project and the Port of Oakland, where the majority of sediment was sourced for this project (I just had this thought that it might be nice to show the distance the sediment traveled by having the port and the restoration site in the same map).

6.) Humboldt Dunes map showing extent of the Eureka littoral cell and locations of the demonstration sites.

I'm going to reach out to people to see if I can get shapefiles.

Let me know if there are other questions or info needs.

**Comment by connorshank** [comment]
In summary, I think it would be great to have 6 maps. One that has all 5 case study locations on a map for the introduction (dots on a map) and one for each case study that is more zoomed in to show a bit more of the setting (check out the ones for Humboldt and surfer's point, maybe something similar to those two).

tha 5 case studies are:
•         Humboldt Coastal Dune Vulnerability and Adaptation Climate Ready Project, 
•         San Francisco Bay Living Shorelines: Nearshore Linkages Project, 
•         Hamilton Wetland Restoration Project, 
•         Surfers’ Point Managed Shoreline Retreat Project, and 
•         Seal Beach National Wildlife Refuge Thin-layer Salt Marsh Sediment Augmentation Pilot Project.

I've gone through the report and essentially left in summaries, project details and some of the more spatially oriented photos so that you wouldn't have to wade through the whole thing to get a sense of what we need (I'm happy to share the whole report too if that's better). Essentially I'd like a consistent map figure that accompanies the project details near the top of each case study in addition to some of the more specific site maps (or if your maps replace some of the site maps that's ok too, some of them don't look that good in my opinion). 
It might be a good idea to talk about it or if you have examples to share that might fit this need maybe that is a good place to start? Let me know your preferred approach. I'm available most times this week, except Wednesday.

**Comment by connorshank** [comment]
The finished JPEGs and drafts are located in the following folder:
N:\OCEANS_Program\projects\NaturalShorelineInfrastructure\plots

mxds can be found here:
N:\OCEANS_Program\projects\NaturalShorelineInfrastructure\mxds
