### ISSUE TITLE
Pajaro web map reporting tool draft/mock-up (12/1 flex)

### ISSUE THREAD

**Issue by connorshank** [tnc-ca-geo/gd_intern#112]
Create a mock-up of output for a reporting tool to be used with the Pajaro Compass web app, to be made into a widget.   Use Bay Area Greenprint for guidance/inspiration, the Pajaro version will probably not be as detailed though.   Consider which layers would be most useful for reporting, and what ways the data could be summarized for each.

**Comment by connorshank** [comment]
Carrie, I've added the 'Near me' widget to the Pajaro web app on a trial basis to see how it works.   I think this may be in line with the type of reporting tool you were talking about.   I haven't been able to find a tool (yet) that allows the user to create a polygon and then get a summary of the layers within said polygon, but I will keep looking.   Let me know what you think of this widget for now, it can't interact with all the layer unfortunately, but it is quite useful.   It appears as a button in the upper right-hand side of the map.

**Comment by cschloss** [comment]
Connor - what a cool tool find!  Thanks! I like this as an intermediate solution.

For the reporting widget, we will be working with ESRI developers to create a custom widget that will create the reports.  The work we need to do first though is to mock up a report in word or power point.  So that we can get feedback from the steering committee and the compass network to make sure we are providing the right information in an interpretable and useful way.

Here is a quick example of the type of thing I'm thinking we need to mock up:
![image](https://user-images.githubusercontent.com/11560481/33467411-27c31e88-d609-11e7-88f0-115acd927d54.png)

But we can think creatively, and then see what is feasible - for example, would this be better communicated with a chart in addition to a table?  What context can we provide for metrics that makes the values meaningful?

Happy to have a working session with you to brainstorm!  Thanks for starting to think on this!

**Comment by cschloss** [comment]
Hi Connor this is a great start.  I
[Pajaro Report Mock-up_csComments.pdf](https://github.com/tnc-ca-geo/gd_intern/files/1623580/Pajaro.Report.Mock-up_csComments.pdf)
 put comments on the PDF.  Thanks for taking this on.

**Comment by cschloss** [comment]
Its getting really close!  Thanks for pushing this forward.  My comments are here:
[Pajaro Report Mock-up_v2_csEdits.pdf](https://github.com/tnc-ca-geo/gd_intern/files/1653339/Pajaro.Report.Mock-up_v2_csEdits.pdf)

Can you address these and then schedule a meeting with you, me and Abby to talk through this?

**Comment by cschloss** [comment]
Hi Connor -

TNC is transitioning out of leadership of the Pajaro Compass.  We will still lead the Tools and Analysis for FY19, but as we are ramping down our engagement we can't justify moving forward with new feature development this coming year, so I'm closing this issue.  Thank you for your work on this.  After this transition year, there may be a plan for a watershed coordinator and we will pass the progress we made on this on to them.
