### ISSUE TITLE
NV Duke Partners Web Map Creation (12/1)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#114]
Our NV colleagues and partners need an AGO web map so that they can interact with data layers from the BLM RMP.

Map Package is posted on carogis at Nevada\gdbs\RMP\RMP_webmap_mockup_no_Ventyx.mpk

Tasks:
1. Project data layers into web map compatible projection (WGS_1984_Web_Mercator_Auxiliary_Sphere) using appropriate transformation as necessary
2. Reproduce data layer organization as appears in RMP_webmap_mockup_no_Ventyx.mxd
3. Assign symbology as appears in RMP_webmap_mockup_no_Ventyx.mxd. Update layers that have simple purple symbols with new colors, being consistent for layers that show similar data between groups.
4. Create map service in Energy folder on Stratus. Important: increase # of features to 10000 (from default 1000 setting)
5. Create web map adding each layer individually (to retain layer functionality such as transparency)

**Comment by bcohen27** [comment]
Our desired deadline for first draft is Dec. 1st.

**Comment by connorshank** [comment]
I have created two webmap options, the first contains all the layers added separately (same order as in the mxd) so that the symbology of each can be altered as needed.   The second has the layers added in groups, so the layers cannot be edited individually but are easier to navigate.  Let me know which works best for your purposes.   The data are hosted at the following url: http://stratus-1088065922.us-west-1.elb.amazonaws.com/arcgis/rest/services/Energy/RMP_webmap_publish_no_Ventyx/MapServer

http://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=465b02fb54164f0cafee4b8e8ee1c154
http://tnc.maps.arcgis.com/home/webmap/viewer.html?webmap=e5b8f886c6424119bd994343b87da51a

**Comment by bcohen27** [comment]
Thanks Connor. It may be that we need to create Dynamic Map Layers, so that the individual map layers can be manipulated even if they are part of a group. Can you see what you can learn about Dynamic layers to see:
1. How do we create them? 
2. Do they actually allow us to manipulate them if they are part of a group?

**Comment by connorshank** [comment]
I can look into this today and next week, a cursory look at some of the help pages from Esri tells me this might get a little involved and require some coding, but I'll get back to you when I know more.

**Comment by connorshank** [comment]
Brian,   
I've enabled dynamic layers on the published service, and it looks like I can edit the layers symbology and transparency from my end.   I've shared the webmap with The Nature Conservancy group, let me know if you can make changes to individual layers in the Nevada Duke Partners Version 2 webmap.

**Comment by bcohen27** [comment]
Wow wow wow wow. That is amazing. Well done, and thank you!

Are the data and mxd in a location on carogis where I can access them and manipulate? I am not sure yet which is going to be more efficient - altering the layer names and symbology in the mxd and republishing, or just doing those changes in the web map itself. If the data/mxd is accessible then I can do some testing, and it will be helpful to have access for future updates/changes.

Can you provide a brief explanation of the process to create the dynamic layers? That will be helpful for us going forward as well.

Thanks again for figuring this out!

**Comment by connorshank** [comment]
The location of the mxd service is here: GIS Servers\Stratus Connor Shank Publisher\Energy
(I don't think you would have access to it though, since I was the original publisher)
It is probably easier to just change the layer names and symbols in the webmap itself, rather than re-publishing the service.

I'll go ahead and email you an explanation for enabling dynamic layers using ArcCatalog after the mxd is already published, as well as how to enable them during the publishing process (it looks like the method is pretty much the same).
