### ISSUE TITLE
Develop polygon layer of solar installations in CA desert (1/26 flex)

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#124]
We need to develop a polygon layer of the footprint of solar facilities in the CA desert. 

Attached is a point file of the facilities for which we need polygons: 
[CA_Desert_RE_Solar.gdb.zip](https://github.com/tnc-ca-geo/gd_intern/files/1556543/CA_Desert_RE_Solar.gdb.zip)

1. Create a new polygon feature class within the attached geodatabase, name it Operating_Solar_polygons. Please use GCS_WGS_1984 as the projection.
2. Add a long integer field named "tbl_POC__Unit_ID", and a double field named Acres.
3. Using the Operating_Solar_pts layer as a guide to the location of the solar installations, and the World Imagery Basemap in Arcmap, digitize the perimeter of the solar panels/infrastructure for each project.
4. Note - the locations of the facilities might not always correspond with the point location, so you will need to do google searches on the names of the projects to confirm. The "CA_Plants_Ventyx_NOT_FOR_SHARING_Location_Code" field will give you an indication of the accuracy of the point (1 = great, 4 = really bad).
You can supplement your searching with the map at https://www.seia.org/research-resources/major-solar-projects-list   That map has dates for each facility too, which would be great to add to the dataset in a new field called SEIA_Date
5. You may encounter obvious solar facilities for which there is no corresponding point. Please digitize them and give them a Unit_ID value of 9999
6. You may need to zoom in close in order for the most recent imagery to show up.

Thanks! And let me know if you have any questions. As for timing, whenever you can get to this would be great. We need it by mid-January, but would be great to have as soon as you can get to it.

**Comment by connorshank** [comment]
Brian, I have created a polygon feature class and done my best to capture all solar facilities visible in the world imagery basemap.    Based on the images in google maps, this dataset is probably incomplete, particularly for those facilities built within the last year.    I have also done my best to populate the tbl_POC__Unit_ID field with the corresponding information from the point shapefile.   However, there were a number of instances (especially in the Western Mojave) where it was not clear which points corresponded to which solar facilities.   In order to keep the data as accurate as possible, I followed a few rules of thumb when matching points to polygons:

-  If a point had only one polygon (or very close set of polygons) in its vicinity, OR if a point overlapped a polygon, it was assumed that the solar facility mapped by the polygon was the one referenced by the point.   An effort was made to confirm this by googling the project name and operator name, and in most cases this search was successful.
- If multiple points were close to one or more polygon features, an effort was made to search for the project online and see if a reliable source (i.e. government, EIS, or the operating company's website) had a sufficiently-detailed blueprint or some sort of image that would indicate which solar facilities were exclusive to the project indicated by the point.   In some cases this yielded success.
- Where the corresponding solar facility's polygons were not obvious, the point's Unit_ID was only assigned to a polygon IF it directly overlapped said polygon.

There were also a number of points that were not close to any visible solar features.   The Unit_IDs for these points were not assigned to any polygons.
Shapefiles are located here:
N:\Projects\Solar\gdbs\CA_Desert_RE_Solar.gdb

**Comment by bcohen27** [comment]
Thanks Connor!

I’ve done a quick review and found a few facilities that were not captured in your layer. These points have either NULL or “new” in the Plant Name field.

Sorry for the bad data management, but attached is the data that I have updated.

As next step, please review against the map at https://www.seia.org/research-resources/major-solar-projects-list

**Comment by connorshank** [comment]
Brian,
      I have added the additional solar facilities you pointed out, as well as a few others I spotted in Imperial county.   I have also reviewed most of the other polygons and adjusted some of the information for those that I was able to find more detailed info on.   I have gone through and added the dates from the seia website as well, though as with the POC_Unit_ID there were a number of facilities that I could not confidently match between the two sources, and so I erred on the side of caution.   The updated layer can be found here: 
N:\Projects\Solar\gdbs\CA_Desert_RE_Solar2.gdb\CA_Desert_RE_Solar2.gdb

**Comment by bcohen27** [comment]
Thanks Connor, this is looking terrific.

I reviewed the data and have added some new footprints that I saw in Google Earth.

I updated the Completion date for all of the polygons, including the ones that I have added.

I added the fields Plant_Name and MW to hold the name of the plant and its nameplate capacity. I have filled these in for many of them but not all.

The next step I would like for you to do is to use the seia.org map (https://www.seia.org/sites/default/files/2017-12/mpl.html) to update the polygons that currently have no name or MW data.

Two more new steps (the deadline for these two steps can be 1/19 or later if it ends up taking a while):

  1.  Please add a field named URL, and populate it with the url of the most appropriate website you can find for the plant. This will probably be the site of the developer, though the Wikipedia site would be ok too).
  2.  Please add a field name “Purchaser” and populate it with the entity that purchases the electrons that are generated by the plant. This will require research, but hopefully will be discoverable when doing Step 1.

I foresee this database to be the beginning of a database for the state, and I have yet to think through all of the attributes that we’ll want in it, which is why this is happening in piece-meal. Any ideas that you might have please feel free to share.

I placed the new data in N:\Projects\Solar\gdbs\CA_Desert_RE_Solar2.gdb\Operating_Solar_polygons_v2 (which means I think I inadvertently overwrote what you had in there).

**Comment by bcohen27** [comment]
Next steps:
I have updated the data in N:\Projects\Solar\gdbs\CA_Desert_RE_Solar2.gdb\CA_Desert_RE_Solar2.gdb to reflect some updates I have made.
What remains is to fill out the attributes for polygons that have some but not all of the fields completed, and to add in polygons and attribute data for facilities in Nevada that are not yet in the gdb. The fields of priority importance are: Completion Date, MW, and Plant_Name.
If this can be done within two weeks that would be great.

**Comment by connorshank** [comment]
Brian,   I have added in a few missing solar plants and double-checked the critical fields in the polygon layer (Plant name, Year, MW).   There a still a few odd arrays that don't have all of the fields filled in, as I have yet to locate a reliable source for them.   The majority are good to go though.

**Comment by bcohen27** [comment]
Thanks for all the work on this Connor. I'm calling it good and closing out.
