### ISSUE TITLE
Rooting Depth Database Formatting

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#131]
Hi Connor-  We need some help formatting a database to work well in Excel.  This database came from a PDF file and has lots of wacky formatting issues. I'll send links to the data.

**Comment by kklausmeyer** [comment]
This task is coming from Laura Riege.  She started making the edits and will do the final joining of the data, so please contact her directly with questions.  Here is her email:

Hello all,

Good conversation on Wednesday. I am so glad that there is someone who can help out with the formatting of these excel files so that I can stop being a bottleneck! Thank you Kirk for helping to find a solution.

As discussed, I converted the Fan et al database from pdf to xls, but there’s a lot of formatting needed. I uploaded the in progress excel file to the folder Sally lists below (Box\Groundwater Working Group\Science\Tools\Rooting Depths\TNC Database\Materials for Laura). There’s a read me tab that lists what I’ve done so far and what needs to be done.

I’m happy to use JMP to join all of the files and make the summary files we need. That’s easy for me. Getting them formatted was just taking too much time.

Questions?
Feel free to ask.

Thanks!
Laura

**Comment by kklausmeyer** [comment]
Here is the direct link to the Box folder.  https://tnc.app.box.com/folder/41325329446

Here is the name of the file to edit:  Fan-et-al-2017-Root-Depth-Observations_LR.xlsx

There is a PDF file in the folder with a very similar name-  that is the original.

Thanks for your help on this!

**Comment by kklausmeyer** [comment]
Thanks Connor for your help on this!  I've forwarded your work directly to Laura and she will give you feedback on next steps.

**Comment by connorshank** [comment]
3/15 Update:
I took a quick look at Connor’s database and overall it looks good. These are the things Gregg could help with:
1.	I’ll be merging on species name. This should be two words (genus and species, e.g. “Sally liu”) or a genus with “spp” (e.g. “Sally spp”). Any stray commas, letters, symbols or extra words should be eliminated. If he’s not sure, ask him to highlight the cell and I’ll take a look at it.
2.	Rows 2003 – 2017 do not have any species names. This should be checked against the original pdf file. If that’s the way it is in the original file, then these records can be deleted.
3.	The column “texture/type” seems to refer to soil type. I think we’d like to include this in our database. The text appears to be wrapped or have extra carriage returns in it. Kirk had a way to remove carriage returns so that the text does not wrap.
