### ISSUE TITLE
BirdReturns Spring 2018 mapping

### ISSUE THREAD

**Issue by connorshank** [tnc-ca-geo/gd_intern#143]
Update fieldMaster layer for Spring 2018 bids as they come in through Salesforce.

**Comment by ka78** [comment]
@connorshank - Julia and the field team visited all the duck clubs last week and confirm that they're contracting with the following via email:

> 166 – Anchor
> 175 – Chris Dobson/dairy
> 176 – Royal – northern pond only
> 178 – Field of Dreams
> 179 – Stone Creek
> 180 – Cortina 
> Also, We are not accepting 174/Dobson Two Mile Property because he can’t keep water on into April. He didn’t understand about the dates. There may be one more called Bell Outing. More on this next week. 

Last week I coded all the duck club fields as ENRO so that they'd show up on the AGO (for their field outing). Now that they've decided which clubs to contract with we need to edit my "ENRO" records and code them to accurately reflect the decisions made last week. Can you please go through Julia's email, along with the bids in Salesforce and review/correct the ENRO/BID codes?  Please lmk when you're done and I'll publish the AGO. Thanks, Katie

**Comment by connorshank** [comment]
I have double checked and updated all the duck club fields based on Julia's email.   All the fields that she listed as accepted are now entered as ENRO in Spr_2018 field in GIS.   The 18-SD-174 fields have also been changed to BID status.

**Comment by ka78** [comment]
thanks @connorshank - I'll push these to AGO. 
leaving this open because they'll be more

**Comment by ka78** [comment]
as per Julia's email, please create contract maps for the duck clubs. note: the latest bid to come in was mistakenly assigned "SR" but will be changed to "SD" in the bid ID... thank you.
