### ISSUE TITLE
Data Mgmt - migrate Santa Clara River projects from San Diego to CARO

### ISSUE THREAD

**Issue by bcohen27** [tnc-ca-geo/gd_intern#19]
Need to have the projects (.mxds and data) for the Santa Clara River migrated from the San Diego server to CARO so that the work can be continued by someone in the San Francisco office.

**Comment by cgrainger431** [comment]
Hi Brian, 

Do you still want help with this project?

**Comment by bcohen27** [comment]
Hi Cori

Yes, I believe the Water program needs this done. No pressing deadline.

Brian

**Comment by cgrainger431** [comment]
Okay great.  Would you want to connect when you have some free time to go over what I need to do for this?  I know everyone is really busy with the holidays, so no rush. 

Thanks!
-Cori

**Comment by megrwebb** [comment]
Has this happened?  I'm looking for Santa Clara River watershed nodes (e.g. Sespe Node) to add to a board book deal map?  This is due today/this morning, so let me know if we might have this.  Thanks! Megan

**Comment by ka78** [comment]
@bcohen27 -- I have set Kat Selm and Susan North up with access to CAROGIS, and created a Santa Clara River and Coasts SCRC project folder for them.  They will Remote Desktop into CAROGIS to take care of their GIS needs in a self-service manner.  They were asking about existing/historic/site-specific data for this project and I thought we should resurrect this issue, and perhaps have them organize the data once it's on CAROGIS rather than have Connor do it.  

Do you have the SCRC data on an external HD, or can you get it to Susan North somehow? She could upload it to CAROGIS and then she and Kat could organize it.

They just gained access to CAROGIS and I imagine would be ready to move/org data in a couple of weeks.  Can you assist them with getting their hands on your Santa Clara River and Coasts archive?

**Comment by bcohen27** [comment]
I have copied the data and mxds over to carogis.

The MXDs are in D:\GIS\South_Coast\Projects\Lav\Mxds\LAV

The data are in D:\GIS\South_Coast\Projects\Lav\Geo_data\LAV

I maintained these paths as they mimic what I have, just for consistency. However, my drive is “N:”, so the mxds on carogis will not work as we are using drive “D:”

This will be a process of going through the data/mxds/maps to figure out where we want to invest the time to fix the mxds.

**Comment by ka78** [comment]
Closing - Susan North and Kat Selm worked with Brian on this (they are the users, and recently gained access to Carogis).
