### ISSUE TITLE
Print springs poster and FedEx to Stephanie D.

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/gd_intern#234]
Hi Connor-  Can you plot this file: https://tnc.box.com/s/m4a7p5dh0577rifapwf9skvxfcu02zbp and send it via Fed Ex to Stephanie Dashiel.  I'll add the address to this issue when I have it.  Brian made the file so contact him if you have questions.

**Comment by kklausmeyer** [comment]
Stephanie Dashiell
59920 Onaga Trail
Joshua Tree, CA 92252

**Comment by kklausmeyer** [comment]
Poster needs to arrive by Friday so 2-day shipping should work if it goes out today before 4pm.

**Comment by megrwebb** [comment]
@kklausmeyer, @connorshank,
Our HP plotter is out of paper.  I'll be in SF tomorrow and will load a new roll.  So, you'll need to do 1-day shipping unless you want to try to load a roll today, but be warned our plotter is a sensitive beast and really likes to jam paper.  If you would like to attempt to load a roll yourself, let me know and I'll try to direct you to some documentation to do this manually (works better) rather than following the automatic prompts from the plotter.

**Comment by bcohen27** [comment]
Looks like the Sacramento plotter might be functional, so I'll try to use that instead. Thanks for the help!
