### ISSUE TITLE
birdreturns bid mapping Nov 3-9

### ISSUE THREAD

**Issue by ka78** [tnc-ca-geo/gd_intern#32]
Context:
@cgrainger431, the bidding period for the Spring program will run Nov 3-9.  This will be the first time growers will bid using the online bidding form, and their bids (and map attachments) will push into Salesforce as bid records. 

The work:
Bids, and map attachments will need to be used to add new fields to the master field dataset, and also to populate fields with their Spring program option.  The heaviest work days for you will likely be Nov 8 and 9.  I requested a Salesforce account for you; I believe it was created yesterday.  I'll set up a meeting to walk through Salesforce with you. Thanks in advance!

**Comment by cgrainger431** [comment]
Hi Katie,

The shapefile I have been inputting all of the bid information into is in the Master_Field_2016_November folder and is called br_fields_master_2016_Nov_Multi.  The only bids not in there are 011, 037 and 038 because there are outstanding questions for Julia about those fields. 

I will probably be checking my email sporadically so if you have a question, you can send them along and I will respond when I see them!

**Comment by ka78** [comment]
@cgrainger431 - I'm reopening this, because as the team finalizes the winning bids for Spring, some of the bids will be accepted contingent on a reduction of the original bid acres.  I've created a View in Salesforce, in the Bid tab, called "Current Program Period Status".  When Julia/Jordan accept bids, they'll mark Status as "Accepted" and when a bid is accepted based on an acreage change or reduction, they'll put the details in the Bid Notes fields.  When there is an accepted bid that needs a change, will you please make the adjustments to the master field layer?
