### ISSUE TITLE
Infographics for land team

### ISSUE THREAD

**Issue by cgrainger431** [tnc-ca-geo/gd_intern#55]
Tanu has asked me to create several infographics for a report she is putting together with Rodd and will add more information to this post about what is needed.  The drafts are due around April 7th.

**Comment by TB2016** [comment]
Thanks Cori and Katie. Cori, correct the 1st draft due date to April 12th, Final is due 21st. I will make very basic infograph, based on Rodd request. Am using April 12th as our internal deadline to  so we have some time for a round of feed back n corrections. Just want to plan ahead so that we are not too stressed around deadline. I am hoping to get some feedback from Rodd after 1st draft so that we can complete it on our end by 18th. Thanks Tanu

**Comment by TB2016** [comment]
this data is not ready yet Cori.. jsut keeping you in the loop. Thanks T

**Comment by TB2016** [comment]
Cori -- I have the dataset for this to start working on..  I will upload data in GDRIVE

**Comment by TB2016** [comment]
Hi Cori -- tagging this as time sensitive, and here is the link to the datasets 

https://drive.google.com/drive/folders/0B_okb3ppkxGcZDdQMURjTG9kS3c?usp=sharing

Task 1 Create two Interim product with Maps of 8 variables normalized by Max and Median
Task 2  Use one of the above product on webmap
